# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poultry-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poultry-app
      tier: frontend
  template:
    metadata:
      labels:
        app: poultry-app
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: sakthivel404/frontend-app-poultry:latest
          ports:
            - containerPort: 80
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poultry-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poultry-app
      tier: backend
  template:
    metadata:
      labels:
        app: poultry-app
        tier: backend
    spec:
      containers:
        - name: backend
          image: sakthivel404/backend-app-poultry:latest
          env:
            - name: DATABASE_HOST
              value: "mysql"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "root"
            - name: DATABASE_NAME
              value: "poultrydb"
          ports:
            - containerPort: 8080
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poultry-app-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poultry-app
      tier: mysql
  template:
    metadata:
      labels:
        app: poultry-app
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: sakthivel404/mysql-app-poultry:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "poultrydb"
          ports:
            - containerPort: 3306
