apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poultry-app-hpa
  namespace: poultry-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poultry-app-frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
