# ingress.yaml

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "poultry-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewriteTarget }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.paths.frontend }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "poultry-app.frontend.fullname" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
          - path: {{ .Values.ingress.paths.backend }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "poultry-app.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
