apiVersion: v1
kind: Service
metadata:
  name: poultry-app-frontend
  namespace: poultry-app
spec:
  selector:
    app: poultry-app
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poultry-app-backend
  namespace: poultry-app
spec:
  selector:
    app: poultry-app
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: poultry-app-mysql
  namespace: poultry-app
spec:
  selector:
    app: poultry-app
    tier: mysql
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
