mysql:
  image:
    repository: mysql-app-poultry
    tag: latest
  rootPasswordSecret: mysql-root-password-secret  # Reference to the Secret containing MySQL root password
  service:
    port: 3306


backend:
  image:
    repository: backend-app-poultry  # Local image built in Minikube Docker
    tag: latest
  service:
    port: 8080  # Port where backend app will be exposed

mysql:
  image:
    repository: mysql-app-poultry  # Local image built in Minikube Docker
    tag: latest
  rootPasswordSecret: mysql-root-password-secret  # Secret containing MySQL root password
  service:
    port: 3306  # MySQL service port

# Service Account settings
serviceAccount:
  create: true  # This will create a service account

# Autoscaling settings for the backend
autoscaling:
  enabled: true  # Enable autoscaling
  minReplicas: 1
  maxReplicas: 5

# Ingress settings for routing traffic to frontend and backend
ingress:
  enabled: true
  host: poultry-app.local  # Host for the ingress rule
  # Define paths for frontend and backend
  paths:
    frontend: /frontend
    backend: /backend
  rewriteTarget: /  # Path rewrite rule (optional, if you want to route cleanly)
