apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullstack-app.fullname" . }}
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ index .Values.ingress.hosts 0 "host" }}
      http:
        paths:
          - path: {{ index .Values.ingress.hosts 0 "paths" 0 "path" }}
            pathType: {{ index .Values.ingress.hosts 0 "paths" 0 "pathType" | default "Prefix" }}
            backend:
              service:
                name: {{ index .Values.ingress.hosts 0 "paths" 0 "backend" "serviceName" }}
                port:
                  number: {{ index .Values.ingress.hosts 0 "paths" 0 "backend" "servicePort" }}
