# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080 # Matches your input service port
      targetPort: {{ .Values.frontend.service.port }}
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000 # Matches your input service port
      targetPort: {{ .Values.backend.service.port }}
---
