---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}  # LoadBalancer or ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}  # Make sure this selector matches your pod labels
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 8080  # External port to access frontend service
      targetPort: {{ .Values.frontend.service.port }}  # Matches the port exposed by the frontend pod
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  type: {{ .Values.backend.service.type }}  # ClusterIP or any other type
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}  # Make sure this selector matches your pod labels
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: 5000  # External port to access backend service
      targetPort: {{ .Values.backend.service.port }}  # Matches the port exposed by the backend pod
