frontend:
  image:
    repository: sakthivel404/frontend-app
    tag: latest
  service:
    type: LoadBalancer
    port: 8080

backend:
  image:
    repository: sakthivel404/backend-app
    tag: latest
  service:
    type: ClusterIP
    port: 5000

replicaCount: 1

serviceAccount:
  create: true

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - host: example.com
    paths:
    - path: /
      pathType: Prefix  # Add this line
      backend:
        serviceName: frontend
        servicePort: 8080

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
